language: node_js

node_js:
  - '10'

script:
  - npm run lint
  - npm run build
  - npm run check

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  committer-from-gh: true
  on:
    branch: master
