name: Nightly update Starbucks store data
on:
  schedule:
    # https://crontab.guru/every-night-at-midnight
    - cron: "0 0 * * *"
  push:
    branches:
      - travis

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: git checkout json-update || true
      - run: npm install
      - run: npm run build
      - run: npm run check
      - name: Create Pull Request
        uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "Update Starbucks store data"
          branch: "json-update"
          path: "./"
          commit-message: "Update Starbucks store data"
          author: "sinchang<sinchangwen@gmail.com>"
